// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4HkPmqcaI01V1twSRV2ndJVHvm6A3tsA',
    appId: '1:489698151117:web:3efd496a45cb91d0487784',
    messagingSenderId: '489698151117',
    projectId: 'todo-1999-11-11',
    authDomain: 'todo-1999-11-11.firebaseapp.com',
    storageBucket: 'todo-1999-11-11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDond6iomRQz-jCI0CO8IN6Jy-zPmrDNTs',
    appId: '1:489698151117:android:52d624f4947573e5487784',
    messagingSenderId: '489698151117',
    projectId: 'todo-1999-11-11',
    storageBucket: 'todo-1999-11-11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYauHjuhBVEb5Cn0gV8e1xj7L_AZ55aUQ',
    appId: '1:489698151117:ios:b18f339335d3ea26487784',
    messagingSenderId: '489698151117',
    projectId: 'todo-1999-11-11',
    storageBucket: 'todo-1999-11-11.appspot.com',
    iosClientId: '489698151117-md19jt6j7rpb8dav70u7l7230qt4pu6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYauHjuhBVEb5Cn0gV8e1xj7L_AZ55aUQ',
    appId: '1:489698151117:ios:b18f339335d3ea26487784',
    messagingSenderId: '489698151117',
    projectId: 'todo-1999-11-11',
    storageBucket: 'todo-1999-11-11.appspot.com',
    iosClientId: '489698151117-md19jt6j7rpb8dav70u7l7230qt4pu6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
